import re
import logging
from typing import List, Dict, Any, Tuple

logger = logging.getLogger(__name__)

class CitationValidator:
    def __init__(self):
        # Match citations like [Doc 1], [Doc 2], [1], [2], or [Doc A]
        self.citation_pattern = re.compile(r'\[Doc\s*(\d+)\]|\[(\d+)\]', re.IGNORECASE)

    def validate_and_enrich(self, response_text: str, retrieved_chunks: List[Dict[str, Any]]) -> Tuple[str, List[Dict[str, Any]], bool]:
        """
        Parses LLM response, validates inline citations, and enriches them with real metadata.
        
        Returns:
            - enriched_text: The response text with corrected and clean citations.
            - verified_sources: List of metadata dicts for chunks that were actually cited.
            - all_valid: Boolean indicating if all citations generated by the LLM were valid.
        """
        if not response_text:
            return "", [], True
            
        matches = list(self.citation_pattern.finditer(response_text))
        if not matches:
            return response_text, [], True
            
        verified_sources = []
        source_id_to_metadata = {}
        all_valid = True
        
        # Build maps of index to chunk
        chunks_by_index = {}
        for idx, chunk in enumerate(retrieved_chunks):
            # Index is 1-based for readability
            chunks_by_index[idx + 1] = chunk
            
        # We process matches in reverse order to easily modify the string in place if needed
        # (though we can also just build a list of valid matches)
        valid_citations_in_response = set()
        
        for match in matches:
            groups = match.groups()
            citation_str = groups[0] or groups[1]
            if not citation_str:
                continue
                
            try:
                citation_idx = int(citation_str)
            except ValueError:
                all_valid = False
                continue
                
            # Check if index is valid
            if citation_idx in chunks_by_index:
                chunk = chunks_by_index[citation_idx]
                chunk_id = chunk.get("metadata", {}).get("chunk_id", chunk.get("id"))
                
                # Deduplicate sources cited
                if chunk_id not in [s["chunk_id"] for s in verified_sources]:
                    # Extract source details
                    meta = chunk["metadata"]
                    verified_sources.append({
                        "chunk_id": chunk_id,
                        "brand_name": meta.get("brand_name", "Unknown"),
                        "generic_name": meta.get("generic_name", "Unknown"),
                        "section": meta.get("section", "General").replace("_", " ").title(),
                        "is_essential": meta.get("is_essential", False),
                        "eml_section": meta.get("eml_section", "N/A"),
                        "atc_codes": meta.get("atc_codes", "N/A"),
                        "text_snippet": chunk.get("raw_content", "")[:200] + "..."
                    })
                valid_citations_in_response.add(citation_idx)
            else:
                logger.warning(f"Invalid citation index {citation_idx} generated by LLM (only {len(retrieved_chunks)} docs provided).")
                all_valid = False
                
        # Clean response text: If a citation is invalid, remove it or flag it.
        # Let's replace invalid citations with [Unverified Citation] or remove them,
        # and standardize valid ones to [Doc X].
        # We can construct the final text iteratively.
        enriched_text = response_text
        
        # To avoid index shifts, we can rebuild the text using regex substitution
        def replace_citation(m):
            groups = m.groups()
            cit_str = groups[0] or groups[1]
            try:
                c_idx = int(cit_str)
                if c_idx in chunks_by_index:
                    return f"[Doc {c_idx}]"
                else:
                    return "" # Remove invalid citations or return "[Unverified]"
            except Exception:
                return ""
                
        enriched_text = self.citation_pattern.sub(replace_citation, response_text)
        
        # Strip duplicate spaces created by removed citations
        enriched_text = re.sub(r'\s+', ' ', enriched_text).strip()
        
        # Sort verified sources to match citation order in text
        # Let's sort verified sources by the order they first appear in the text
        appearance_order = []
        for idx in range(1, len(retrieved_chunks) + 1):
            if idx in valid_citations_in_response:
                appearance_order.append(idx)
                
        sorted_sources = []
        for idx in appearance_order:
            chunk = chunks_by_index[idx]
            chunk_id = chunk.get("metadata", {}).get("chunk_id", chunk.get("id"))
            for src in verified_sources:
                if src["chunk_id"] == chunk_id:
                    sorted_sources.append(src)
                    break
                    
        return enriched_text, sorted_sources, all_valid

if __name__ == "__main__":
    validator = CitationValidator()
    test_text = "Metformin is used to treat type-2 diabetes [Doc 1]. It might interact with Ibuprofen [Doc 3]. And some fake citation [Doc 9]."
    test_chunks = [
        {"chunk_id": "m1", "text": "", "raw_content": "Metformin for diabetes.", "metadata": {"brand_name": "Glucophage", "generic_name": "Metformin", "section": "indications_and_usage"}},
        {"chunk_id": "m2", "text": "", "raw_content": "Metformin dosage is 500mg.", "metadata": {"brand_name": "Glucophage", "generic_name": "Metformin", "section": "dosage_and_administration"}},
        {"chunk_id": "m3", "text": "", "raw_content": "Warnings: Avoid combination with ibuprofen.", "metadata": {"brand_name": "Glucophage", "generic_name": "Metformin", "section": "warnings"}},
    ]
    clean_text, sources, valid = validator.validate_and_enrich(test_text, test_chunks)
    print("Cleaned text:", clean_text)
    print("Valid citations overall:", valid)
    print("Verified sources count:", len(sources))
    for s in sources:
        print(f"  Cited: {s['brand_name']} ({s['section']})")
